@baseUrl = http://localhost:3333
@authToken = {{authenticate.response.body.access_token}}
@refreshToken = {{authenticate.response.body.refresh_token}}

# @name create_account
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Diego Fernandes",
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}

###

# @name authenticate
POST {{baseUrl}}/sessions
Content-Type: application/json

{
  "email": "diego@rocketseat.com.br",
  "password": "123456"
}

###

# @name create_question
POST {{baseUrl}}/questions
Content-Type: application/json
Authorization: Bearer {{authToken}}

{
  "title": "Nova perguntdawa",
  "content": "Teste",
  "attachments":[]
}

###

# @name refresh_token
POST {{baseUrl}}/sessions/refresh
Content-Type: application/json

{
  "refresh_token": "{{refreshToken}}"
}

###

# @name fetch_recent_questions
GET {{baseUrl}}/questions?page=1
Content-Type: application/json
Authorization: Bearer {{authToken}}
