services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: leggal-pg
    environment:
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: leggal
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/pg:/data/postgres
    networks:
      - custom_net

  cache:
      container_name: leggal-cache
      image: redis
      ports:
        - 6379:6379
      volumes:
        - ./data/redis:/data

      networks:
        - custom_net
  nest:
    build: .
    volumes:
      - .:/home/node/app
    ports:
      - 3333:3333
    depends_on:
      - postgres
      - cache
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge
    name: forum_network

